"""Minecraft test harness contracts for PD Agent v0.2."""

from __future__ import annotations

from .contracts import (
    MinecraftEvidenceKind,
    MinecraftEvidenceReference,
    MinecraftEvidencePaths,
    MinecraftLaunchPlan,
    MinecraftProcessEvidence,
    MinecraftRuntimeEvidence,
    MinecraftObservationType,
    MinecraftObservationStatus,
    MinecraftObservationRequest,
    MinecraftObservationResult,
    ObservationRequest,
    ObservationResult,
    CommandInvocation,
    CommandResult,
    PersistencePhase,
    PersistenceScenario,
    validate_item_component_profile,
    validate_block_entity_profile,
    validate_inventory_profile,
    validate_tag_membership_profile,
    validate_recipe_match_profile,
    validate_loot_result_profile,
    MinecraftTargetMetadata,
    MinecraftTestResult,
    MinecraftTestSpec,
    MinecraftTestStatus,
)
from .errors import (
    MinecraftTestError,
    MinecraftTestValidationError,
    UnsupportedMinecraftEnvironmentError,
)
from .runner import MinecraftTestRunner, PersistenceRunResult

__all__ = [
    "MinecraftEvidencePaths",
    "MinecraftEvidenceKind",
    "MinecraftEvidenceReference",
    "MinecraftLaunchPlan",
    "MinecraftProcessEvidence",
    "MinecraftObservationType",
    "MinecraftObservationStatus",
    "MinecraftObservationRequest",
    "MinecraftObservationResult",
    "ObservationRequest",
    "ObservationResult",
    "CommandInvocation",
    "CommandResult",
    "PersistencePhase",
    "PersistenceScenario",
    "validate_item_component_profile",
    "validate_block_entity_profile",
    "validate_inventory_profile",
    "validate_tag_membership_profile",
    "validate_recipe_match_profile",
    "validate_loot_result_profile",
    "MinecraftRuntimeEvidence",
    "MinecraftTargetMetadata",
    "MinecraftTestError",
    "MinecraftTestResult",
    "MinecraftTestRunner",
    "PersistenceRunResult",
    "MinecraftTestSpec",
    "MinecraftTestStatus",
    "MinecraftTestValidationError",
    "UnsupportedMinecraftEnvironmentError",
]
