minecraft_version=1.21.11
mappings_version=1.21.11+build.6
fabric_api_version=0.141.6+1.21.11
loader_version=0.19.3
loom_version=1.13.3
mod_version=1.0.0
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8
